version: "3.3"
services:
  encryption_service:
    build: .
    image: 'encryption_service_image:latest'
    container_name: encryption_service
    volumes:
      - C:\Users\geoman\Videos\Repos\EncryptionService\shared_folder:/home/docker_conda_template/shared_folder
    restart: always
    ports:
      - '5000:5000'